#!/usr/bin/env python3
"""
Interactive environment setup script for the backend
"""

import os
import sys
import secrets

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_urlsafe(32)

def setup_environment():
    """Interactive environment setup"""
    print("=== Backend Environment Setup ===\n")
    
    # Check if .env already exists
    if os.path.exists('.env'):
        response = input("A .env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return False
    
    print("This script will help you set up the required environment variables.")
    print("You'll need your Supabase project credentials.\n")
    
    # Get Supabase URL
    print("1. Supabase Project URL")
    print("   Go to your Supabase dashboard → Settings → API")
    print("   Copy the 'Project URL' (looks like: https://abcdefghijklmnop.supabase.co)")
    supabase_url = input("   Enter your Supabase URL: ").strip()
    
    if not supabase_url.startswith('https://'):
        print("   ERROR: URL should start with https://")
        return False
    
    # Get Supabase anon key
    print("\n2. Supabase Anon Key")
    print("   From the same API settings page, copy the 'anon public' key")
    supabase_key = input("   Enter your Supabase anon key: ").strip()
    
    if not supabase_key.startswith('eyJ'):
        print("   WARNING: Key should start with 'eyJ'")
    
    # Get Supabase service key (optional)
    print("\n3. Supabase Service Key (Optional but recommended)")
    print("   From the same API settings page, copy the 'service_role' key")
    supabase_service_key = input("   Enter your Supabase service key (or press Enter to skip): ").strip()
    
    # Get Gemini API key (optional)
    print("\n4. Gemini API Key (Optional - for AI transcript generation)")
    print("   Get this from Google AI Studio: https://makersuite.google.com/app/apikey")
    gemini_key = input("   Enter your Gemini API key (or press Enter to skip): ").strip()
    
    # Generate secret key
    secret_key = generate_secret_key()
    print(f"\n5. Generated Flask Secret Key: {secret_key}")
    
    # Create .env content
    env_content = f"""# Backend Environment Variables
# Generated by setup_env.py

# Database Configuration
DATABASE_URL=sqlite:///instance/classroom_assistant.db

# Flask Configuration
SECRET_KEY={secret_key}
FLASK_ENV=development

# Supabase Configuration (Required for file storage)
SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}
SUPABASE_SERVICE_KEY={supabase_service_key}

# AI Services (Optional)
GEMINI_API_KEY={gemini_key}
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("\n✅ .env file created successfully!")
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        return False
    
    # Test the configuration
    print("\n=== Testing Configuration ===")
    
    # Set environment variables
    os.environ['SUPABASE_URL'] = supabase_url
    os.environ['SUPABASE_KEY'] = supabase_key
    os.environ['SUPABASE_SERVICE_KEY'] = supabase_service_key
    os.environ['DATABASE_URL'] = 'sqlite:///instance/classroom_assistant.db'
    os.environ['SECRET_KEY'] = secret_key
    if gemini_key:
        os.environ['GEMINI_API_KEY'] = gemini_key
    
    # Run environment check
    print("Running environment check...")
    try:
        from check_env import check_env_vars
        env_ok = check_env_vars()
    except Exception as e:
        print(f"Error running environment check: {e}")
        env_ok = False
    
    if env_ok:
        print("\n🎉 Setup completed successfully!")
        print("\nNext steps:")
        print("1. Make sure your Supabase project has a 'lectures' bucket")
        print("2. Run: python test_supabase.py")
        print("3. Start the backend: python app.py")
        return True
    else:
        print("\n⚠️  Setup completed but environment check failed.")
        print("Please check your Supabase credentials and try again.")
        return False

def main():
    """Main function"""
    print("Backend Environment Setup Script")
    print("===============================\n")
    
    try:
        success = setup_environment()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\nError during setup: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
